sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - master
before_deploy:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: puzzle.sitcon.party
  local_dir: dist/
  on:
    branch: master
